#pragma once

#define M_FOREGROUND_BLACK 0x00
#define M_FOREGROUND_BLUE 0x01
#define M_FOREGROUND_GREEN 0x02
#define M_FOREGROUND_CYAN 0x03
#define M_FOREGROUND_RED 0x04
#define M_FOREGROUND_MAGENTA 0x05
#define M_FOREGROUND_BROWN 0x06
#define M_FOREGROUND_LIGHTGRAY 0x07
#define M_FOREGROUND_DARKGRAY 0x08
#define M_FOREGROUND_LIGHTBLUE 0x09
#define M_FOREGROUND_LIGHTGREEN 0x0A
#define M_FOREGROUND_LIGHTCYAN 0x0B
#define M_FOREGROUND_LIGHTRED 0x0C
#define M_FOREGROUND_LIGHTMAGENTA 0x0D
#define M_FOREGROUND_YELLOW 0x0E
#define M_FOREGROUND_WHITE 0x0F

#define M_BACKGROUND_BLACK 0x00
#define M_BACKGROUND_BLUE 0x10
#define M_BACKGROUND_GREEN 0x20
#define M_BACKGROUND_CYAN 0x30
#define M_BACKGROUND_RED 0x40
#define M_BACKGROUND_MAGENTA 0x50
#define M_BACKGROUND_BROWN 0x60
#define M_BACKGROUND_LIGHTGRAY 0x70
#define M_BACKGROUND_BLINKINGBLACK 0x80
#define M_BACKGROUND_BLINKINGBLUE 0x90
#define M_BACKGROUND_BLINKINGGREEN 0xA0
#define M_BACKGROUND_BLINKINGCYAN 0xB0
#define M_BACKGROUND_BLINKINGRED 0xC0
#define M_BACKGROUND_BLINKINGMAGENTA 0xD0
#define M_BACKGROUND_BLINKINGYELLOW 0xE0
#define M_BACKGROUND_BLINKINGWHITE 0xF0